language: php

php:
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --dev
  - mkdir -p build/logs

script: ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
